/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "hallEffectSensor.h"
#include "hallEffectSensor_aliases.h"
#include "LCD.h"
#include "LED_Status.h"
#include "LED_Status_aliases.h"
#include "hallTickCounter.h"
#include "hallEffect_ISR.h"
#include "hallTickTimer.h"
#include "deBounce.h"
#include "pushButton.h"
#include "pushButton_aliases.h"
#include "LED.h"
#include "LED_aliases.h"
#include "SyncOut.h"
#include "SyncOut_aliases.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "PWM_GateVoltage.h"
#include "PWM_clock.h"
#include "MOSFET_Gate.h"
#include "MOSFET_Gate_aliases.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

